Traceback (most recent call last):
  File "object_detection_demo_ssd_async.py", line 210, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_ssd_async.py", line 105, in main
    exec_net = plugin.load(network=net, num_requests=2)
  File "ie_api.pyx", line 389, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 400, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Can not init USB device: NC_DEVICE_NOT_FOUND
find: ‘/tmp/systemd-private-f18908436072423f88ba6ace72f6fd74-colord.service-RziyKm’: Permission denied
find: ‘/tmp/systemd-private-f18908436072423f88ba6ace72f6fd74-rtkit-daemon.service-j7uKgF’: Permission denied
